"""empty message

Revision ID: 4d03347f46d8
Revises: 5c8c899c0e98
Create Date: 2022-07-08 19:03:50.302723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d03347f46d8'
down_revision = '5c8c899c0e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aws_profile_img_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aws_profile_img_key')
    # ### end Alembic commands ###
