"""empty message

Revision ID: 5c8c899c0e98
Revises: ae85775b064d
Create Date: 2022-07-08 18:30:14.674290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8c899c0e98'
down_revision = 'ae85775b064d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('aws_img_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'aws_img_key')
    # ### end Alembic commands ###
