"""empty message

Revision ID: 801cce000f6b
Revises: d7af3f8817cd
Create Date: 2022-02-22 11:21:55.047933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801cce000f6b'
down_revision = 'd7af3f8817cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('img_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'img_url')
    # ### end Alembic commands ###
