"""empty message

Revision ID: b08957b06615
Revises: f3ed8f2d0bdf
Create Date: 2022-02-20 18:45:21.525927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08957b06615'
down_revision = 'f3ed8f2d0bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'created_at')
    # ### end Alembic commands ###
