"""empty message

Revision ID: b400161d7ddb
Revises: b08957b06615
Create Date: 2022-02-20 22:09:47.966444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b400161d7ddb'
down_revision = 'b08957b06615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_cost')
    # ### end Alembic commands ###
